"""Standardized subject lists and class name mappings for the school.

Used by management commands to create per-class/per-term Subject records
and to compute session aggregates.
"""

# Mapping of class code -> list of (abbr, full name)
STANDARD_SUBJECTS = {
    # Pre-school / Nursery
    'PS': [
        ('NUM', 'Number Work'),
        ('LTR', 'Letter Work'),
        ('HLH', 'Health Habit'),
        ('SOH', 'Social Habit'),
        ('CCA', 'Cultural & Creative Arts'),
        ('RLS', 'Religious Studies'),
        ('PHN', 'Phonics'),
        ('HWR', 'Handwriting'),
        ('RHY', 'Rhymes'),
        ('SCI', 'Science'),
    ],
    'N1': [
        ('NUM', 'Number Work'),
        ('LTR', 'Letter Work'),
        ('SCI', 'Science'),
        ('SOH', 'Social Habit'),
        ('RLS', 'Religious Studies'),
        ('HLH', 'Health Habit'),
        ('CCA', 'Cultural & Creative Arts'),
        ('PHN', 'Phonics'),
        ('RHY', 'Rhymes'),
        ('HWR', 'Handwriting'),
    ],
    'N2': [
        ('NUM', 'Number Work'),
        ('LTR', 'Letter Work'),
        ('SCI', 'Science'),
        ('SOH', 'Social Habit'),
        ('RLS', 'Religious Studies'),
        ('HLH', 'Health Habit'),
        ('CCA', 'Cultural & Creative Arts'),
        ('PHN', 'Phonics'),
        ('RHY', 'Rhymes'),
        ('HWR', 'Handwriting'),
    ],
    'N3': [
        ('NUM', 'Number Work'),
        ('LTR', 'Letter Work'),
        ('SCI', 'Science'),
        ('SOH', 'Social Habit'),
        ('RLS', 'Religious Studies'),
        ('HLH', 'Health Habit'),
        ('CCA', 'Cultural & Creative Arts'),
        ('PHN', 'Phonics'),
        ('RHY', 'Rhymes'),
        ('HWR', 'Handwriting'),
    ],

    # Basic (Primary)
    'B1': [
        ('ENG', 'English Studies'),
        ('MAT', 'Mathematics'),
        ('SOC', 'Social Studies'),
        ('SCI', 'Basic Science'),
        ('PHE', 'Physical & Health Education'),
        ('CCA', 'Cultural & Creative Arts'),
        ('RLS', 'Religious Studies'),
        ('HIS', 'Nigerian History'),
        ('HWR', 'Handwriting'),
        ('QTR', 'Quantitative Reasoning'),
        ('VBR', 'Verbal Reasoning'),
        ('MUS', 'Music'),
    ],
    'B2': [
        ('ENG', 'English Studies'),
        ('MAT', 'Mathematics'),
        ('SOC', 'Social Studies'),
        ('SCI', 'Basic Science'),
        ('PHE', 'Physical & Health Education'),
        ('CCA', 'Cultural & Creative Arts'),
        ('RLS', 'Religious Studies'),
        ('HIS', 'Nigerian History'),
        ('MUS', 'Music'),
        ('HWR', 'Handwriting'),
        ('TEC', 'Basic Technology'),
        ('AGR', 'Agricultural Science'),
        ('CIV', 'Civic Education'),
        ('HME', 'Home Economics'),
        ('SEC', 'Security Education'),
        ('ICT', 'Computer Science / ICT'),
    ],
    'B3': [
        ('ENG', 'English Studies'),
        ('MAT', 'Mathematics'),
        ('AGR', 'Agricultural Science'),
        ('PHE', 'Physical & Health Education'),
        ('HME', 'Home Economics'),
        ('SOC', 'Social Studies'),
        ('RLS', 'Religious Studies'),
        ('MUS', 'Music'),
        ('CCA', 'Cultural & Creative Arts'),
        ('ICT', 'Computer Science / ICT'),
        ('HWR', 'Handwriting'),
        ('SEC', 'Security Education'),
        ('TEC', 'Basic Technology'),
        ('SCI', 'Basic Science'),
        ('CIV', 'Civic Education'),
        ('HIS', 'Nigerian History'),
    ],
    'B4': [
        ('ENG', 'English Studies'),
        ('FRN', 'French'),
        ('MAT', 'Mathematics'),
        ('AGR', 'Agricultural Science'),
        ('PHE', 'Physical & Health Education'),
        ('HME', 'Home Economics'),
        ('SOC', 'Social Studies'),
        ('RLS', 'Religious Studies'),
        ('MUS', 'Music'),
        ('CCA', 'Cultural & Creative Arts'),
        ('ICT', 'Computer Science'),
        ('HWR', 'Handwriting'),
        ('SEC', 'Security Education'),
        ('TEC', 'Basic Technology'),
        ('SCI', 'Basic Science'),
        ('CIV', 'Civic Education'),
        ('HIS', 'Nigerian History'),
    ],
    'B5': [
        ('ENG', 'English Studies'),
        ('FRN', 'French'),
        ('MAT', 'Mathematics'),
        ('AGR', 'Agricultural Science'),
        ('PHE', 'Physical & Health Education'),
        ('HME', 'Home Economics'),
        ('SOC', 'Social Studies'),
        ('RLS', 'Religious Studies'),
        ('MUS', 'Music'),
        ('CCA', 'Cultural & Creative Arts'),
        ('ICT', 'Computer Science'),
        ('HWR', 'Handwriting'),
        ('SEC', 'Security Education'),
        ('TEC', 'Basic Technology'),
        ('SCI', 'Basic Science'),
        ('CIV', 'Civic Education'),
        ('HIS', 'Nigerian History'),
    ],
    'B6': [
        ('ENG', 'English Studies'),
        ('FRN', 'French'),
        ('MAT', 'Mathematics'),
        ('AGR', 'Agricultural Science'),
        ('PHE', 'Physical & Health Education'),
        ('HME', 'Home Economics'),
        ('SOC', 'Social Studies'),
        ('RLS', 'Religious Studies'),
        ('MUS', 'Music'),
        ('CCA', 'Cultural & Creative Arts'),
        ('ICT', 'Computer Science'),
        ('HWR', 'Handwriting'),
        ('SEC', 'Security Education'),
        ('TEC', 'Basic Technology'),
        ('SCI', 'Basic Science'),
        ('CIV', 'Civic Education'),
        ('HIS', 'Nigerian History'),
    ],

    # JSS
    'J1': [
        ('ENG', 'English Language'),
        ('MAT', 'Mathematics'),
        ('CCA', 'Cultural & Creative Arts'),
        ('RLS', 'Religious Studies'),
        ('FRN', 'French'),
        ('SCI', 'Integrated Science'),
        ('HIS', 'Nigerian History'),
        ('SOC', 'Social & Citizenship Studies'),
        ('BUS', 'Business Studies'),
        ('ICT', 'Digital Technology'),
        ('MUS', 'Music'),
        ('PHE', 'Physical & Health Education'),
        ('HOR', 'Horticulture & Crop Production'),
    ],
    'J2': [
        ('ENG', 'English Language'),
        ('MAT', 'Mathematics'),
        ('PHE', 'Physical & Health Education'),
        ('SOC', 'Social Studies'),
        ('MUS', 'Music'),
        ('RLS', 'Religious Studies'),
        ('BUS', 'Business Studies'),
        ('CCA', 'Cultural & Creative Arts'),
        ('SCI', 'Basic Science'),
        ('HIS', 'Nigerian History'),
        ('FRN', 'French'),
        ('AGR', 'Agricultural Science'),
        ('HME', 'Home Economics'),
        ('SEC', 'Security Education'),
        ('TEC', 'Basic Technology'),
        ('CIV', 'Civic Education'),
        ('ICT', 'Computer Science'),
    ],
    'J3': [
        ('ENG', 'English Language'),
        ('MAT', 'Mathematics'),
        ('PHE', 'Physical & Health Education'),
        ('SOC', 'Social Studies'),
        ('MUS', 'Music'),
        ('RLS', 'Religious Studies'),
        ('BUS', 'Business Studies'),
        ('CCA', 'Cultural & Creative Arts'),
        ('SCI', 'Basic Science'),
        ('HIS', 'Nigerian History'),
        ('FRN', 'French'),
        ('AGR', 'Agricultural Science'),
        ('HME', 'Home Economics'),
        ('SEC', 'Security Education'),
        ('TEC', 'Basic Technology'),
        ('CIV', 'Civic Education'),
        ('ICT', 'Computer Science'),
    ],

    # Senior Secondary
    'S1': [
        ('ENG', 'English Language'),
        ('MAT', 'Mathematics'),
        ('FUM', 'Further Mathematics'),
        ('ECO', 'Economics'),
        ('PHY', 'Physics'),
        ('CHE', 'Chemistry'),
        ('BIO', 'Biology'),
        ('GEO', 'Geography'),
        ('AGR', 'Agricultural Science'),
        ('ICT', 'ICT'),
        ('LSF', 'Livestock & Farming'),
        ('HCE', 'Heritage & Citizenship Education'),
        ('TDR', 'Technical Drawing'),
    ],
    'S2': [
        ('ENG', 'English Language'),
        ('MAT', 'Mathematics'),
        ('FUM', 'Further Mathematics'),
        ('ECO', 'Economics'),
        ('PHY', 'Physics'),
        ('CHE', 'Chemistry'),
        ('BIO', 'Biology'),
        ('GEO', 'Geography'),
        ('AGR', 'Agricultural Science'),
        ('ICT', 'ICT'),
        ('LSF', 'Livestock & Farming'),
        ('HCE', 'Heritage & Citizenship Education'),
        ('TDR', 'Technical Drawing'),
    ],
    'S3': [
        ('ENG', 'English Language'),
        ('MAT', 'Mathematics'),
        ('FUM', 'Further Mathematics'),
        ('ECO', 'Economics'),
        ('PHY', 'Physics'),
        ('CHE', 'Chemistry'),
        ('BIO', 'Biology'),
        ('GEO', 'Geography'),
        ('AGR', 'Agricultural Science'),
        ('ICT', 'ICT'),
        ('LSF', 'Livestock & Farming'),
        ('HCE', 'Heritage & Citizenship Education'),
        ('TDR', 'Technical Drawing'),
    ],
}

# Mapping class code -> human-readable `Student.class_name` values used in the app
CLASS_NAME_BY_CODE = {
    'PS': 'Pre-School',
    'N1': 'Nursery 1',
    'N2': 'Nursery 2',
    'N3': 'Nursery 3',
    'B1': 'Basic 1',
    'B2': 'Basic 2',
    'B3': 'Basic 3',
    'B4': 'Basic 4',
    'B5': 'Basic 5',
    'B6': 'Basic 6',
    'J1': 'JSS 1',
    'J2': 'JSS 2',
    'J3': 'JSS 3',
    'S1': 'SSS 1',
    'S2': 'SSS 2',
    'S3': 'SSS 3',
}
