# Generated by Django 6.0.4 on 2026-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(choices=[('A', 'A (90-100)'), ('B', 'B (80-89)'), ('C', 'C (70-79)'), ('D', 'D (60-69)'), ('E', 'E (50-59)'), ('F', 'F (Below 50)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term')], default='first_term', help_text='Academic term for the grade', max_length=20),
        ),
    ]
