# Generated by Django 6.0.4 on 2026-04-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_letter_grade_alter_grade_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-term', 'student', 'subject'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='semester',
            new_name='term',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
