# Generated by Django 6.0.4 on 2026-04-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_remove_student_email_remove_student_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term')], default='first_term', help_text='Academic term for the behavioral assessment', max_length=20)),
                ('punctuality', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('relationship_with_staff', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('politeness', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('neatness', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('co_operation', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('obedience', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('attentiveness', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('adjustment_in_school', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('relationship_with_peers', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1)),
                ('times_present', models.PositiveIntegerField(default=0, help_text='Number of times present during the term')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_grades', to='grades.student')),
            ],
            options={
                'verbose_name': 'Behavioral Grade',
                'verbose_name_plural': 'Behavioral Grades',
                'ordering': ['-term', 'student'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
