# Generated by Django 6.0.4 on 2026-04-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_behavioralgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, help_text="Student's class (e.g., JSS1A, SS2B)", max_length=50, null=True),
        ),
    ]
