# Generated by Django 6.0.4 on 2026-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_student_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_term', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term')], default='first_term', help_text='Set the currently active academic term for the portal', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Term Setting',
                'verbose_name_plural': 'Term Settings',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, help_text='Unique student ID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='behavioralgrade',
            index=models.Index(fields=['student', 'term'], name='grades_beha_student_24bd34_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'term'], name='grades_grad_student_093856_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject', 'term'], name='grades_grad_subject_da7e56_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['letter_grade'], name='grades_grad_letter__a7ab2b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='grades_stud_last_na_3eef47_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_name'], name='grades_stud_class_n_6dd80a_idx'),
        ),
    ]
