# Generated by Django 6.0.4 on 2026-04-28 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_work',
            field=models.FloatField(default=0, help_text='Class work (max 10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.FloatField(default=0, help_text='Exams (max 60)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='first_test',
            field=models.FloatField(default=0, help_text='1st test (max 10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='homework',
            field=models.FloatField(default=0, help_text='Home work (max 5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='midterm_test',
            field=models.FloatField(default=0, help_text='Mid-term test (max 10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='project',
            field=models.FloatField(default=0, help_text='Project (max 5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='behavioralgrade',
            name='term',
            field=models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('session', 'Session Average')], default='first_term', help_text='Academic term for the behavioral assessment', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='marks',
            field=models.FloatField(default=0, editable=False, help_text='Total marks out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('session', 'Session Average')], default='first_term', help_text='Academic term for the grade', max_length=20),
        ),
        migrations.AlterField(
            model_name='termsetting',
            name='current_term',
            field=models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('session', 'Session Average')], default='first_term', help_text='Set the currently active academic term for the portal', max_length=20),
        ),
    ]
