# Generated by Django 6.0.4 on 2026-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_grade_class_work_grade_exam_grade_first_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects the student is enrolled in for the current term', related_name='students', to='grades.subject'),
        ),
    ]
