# Generated by Django 6.0.4 on 2026-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioralgrade',
            name='relationship_with_staff',
            field=models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Satisfactory'), ('E', 'E - Needs Improvement'), ('F', 'F - Poor')], default='C', max_length=1, verbose_name='Relationship with Staff'),
        ),
        migrations.AlterField(
            model_name='behavioralgrade',
            name='times_present',
            field=models.PositiveIntegerField(default=0, help_text='Number of times present during the term', verbose_name='Times Present'),
        ),
    ]
