# Generated by Django 6.0.4 on 2026-05-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_classpromotionrequest_student_pks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classpromotionrequest',
            new_name='grades_clas_status_9b1691_idx',
            old_name='grades_clas_status_246179_idx',
        ),
        migrations.RemoveField(
            model_name='classpromotionrequest',
            name='student_pks',
        ),
    ]
