# Generated by Django 6.0.4 on 2026-05-05 05:00

import grades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_rename_grades_clas_status_246179_idx_grades_clas_status_9b1691_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behavioralgrade',
            options={'ordering': ['-academic_year', '-term', 'student'], 'verbose_name': 'Behavioral Grade', 'verbose_name_plural': 'Behavioral Grades'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-academic_year', '-term', 'student', 'subject'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RemoveIndex(
            model_name='behavioralgrade',
            name='grades_beha_student_24bd34_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grades_grad_student_093856_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grades_grad_subject_da7e56_idx',
        ),
        migrations.AlterUniqueTogether(
            name='behavioralgrade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='behavioralgrade',
            name='academic_year',
            field=models.CharField(default=grades.models.default_academic_year, help_text='Academic year for this behavioral assessment, e.g. 2025/2026', max_length=9, validators=[grades.models.validate_academic_year]),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(default=grades.models.default_academic_year, help_text='Academic year for this grade, e.g. 2025/2026', max_length=9, validators=[grades.models.validate_academic_year]),
        ),
        migrations.AddField(
            model_name='termsetting',
            name='current_academic_year',
            field=models.CharField(default=grades.models.default_academic_year, help_text='Set the active academic year, e.g. 2025/2026', max_length=9, validators=[grades.models.validate_academic_year]),
        ),
        migrations.AlterUniqueTogether(
            name='behavioralgrade',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='behavioralgrade',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='grades_beha_student_89983a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='grades_grad_student_d6f9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject', 'academic_year', 'term'], name='grades_grad_subject_9d7256_idx'),
        ),
    ]
