# Generated by Django 6.0.4 on 2026-05-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0016_alter_behavioralgrade_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpromotionrequest',
            name='student_pks',
            field=models.JSONField(blank=True, default=list, help_text='Primary keys of individual students selected for promotion'),
        ),
    ]
