# Generated by Django 6.0.4 on 2026-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_classpromotionrequest_student_pks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
