# Generated by Django 6.0.4 on 2026-06-24 01:52

import django.db.models.deletion
import grades.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_student_other_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default=grades.models.default_academic_year, help_text='Academic year for this result publication', max_length=9, validators=[grades.models.validate_academic_year])),
                ('term', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('session', 'Session Average')], default='first_term', help_text='Academic term for this result publication', max_length=20)),
                ('is_fee_cleared', models.BooleanField(default=False, help_text='Allow the student to view or print results after school fees are cleared.')),
                ('is_results_approved', models.BooleanField(default=False, help_text='Require school approval before releasing results to the student portal.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_result_publications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='grades.student')),
            ],
            options={
                'verbose_name': 'Result Publication',
                'verbose_name_plural': 'Result Publications',
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
    ]
