# Generated by Django 6.0.4 on 2026-07-15 13:23

from django.db import migrations, models


def ensure_announcement_index_names(apps, schema_editor):
    connection = schema_editor.connection
    if 'grades_announcement' not in connection.introspection.table_names():
        return

    columns = {
        column.name
        for column in connection.introspection.get_table_description(
            connection.cursor(),
            'grades_announcement',
        )
    }

    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS grades_anno_audienc_cba1cd_idx")
        cursor.execute("DROP INDEX IF EXISTS grades_anno_created_521ac5_idx")
        if {'audience', 'is_active'}.issubset(columns):
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS grades_anno_audienc_2b5283_idx "
                "ON grades_announcement (audience, is_active)"
            )
        if 'created_at' in columns:
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS grades_anno_created_02378e_idx "
                "ON grades_announcement (created_at)"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0021_announcement'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_announcement_index_names, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='announcement',
                    new_name='grades_anno_audienc_2b5283_idx',
                    old_name='grades_anno_audienc_cba1cd_idx',
                ),
                migrations.RenameIndex(
                    model_name='announcement',
                    new_name='grades_anno_created_02378e_idx',
                    old_name='grades_anno_created_521ac5_idx',
                ),
            ],
        ),
    ]
