# Generated by Django 6.0.4 on 2026-07-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0021_announcement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='grades_anno_audienc_2b5283_idx',
            old_name='grades_anno_audienc_cba1cd_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='grades_anno_created_02378e_idx',
            old_name='grades_anno_created_521ac5_idx',
        ),
    ]
